# shared-code.yml
name: Deploy Fargate Application Shared Code

on:
  workflow_run:
    workflows: ["workflowA", "workflowB"]
    types:
      - completed

jobs:
  shared-deploy-fargate-application-jonjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Your shared steps go here
      - name: Shared Step
        run: echo "This is a shared step."
