# workflowA.yml
name: Deploy Fargate Application - ProdStack

on:
    push:
      branches:
        - main 
  
jobs:
  deploy-prodstack:
    runs-on: ubuntu-latest
    steps:
      - name: Run Shared Code
        uses: ./.github/actions/deploy-fargate-app-shared-code.yml
        with:
            STACK_TO_DEPLOY: "ProdStack"


