# workflowA.yml
name: Deploy Fargate Application - DevStack

on:
    push:
      branches:
        - dev 
  
jobs:
  deploy-devstack:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4    
            
      - name: Run Shared Code
        uses: ./.github/actions/deploy-fargate-app-shared-code
        with:
           STACK_TO_DEPLOY: "DevStack"
