# workflowA.yml
name: Deploy Fargate Application - ProdStack

on:
    push:
      branches:
        - main 
  
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: echo "STACK_TO_DEPLOY=ProdStack" >> $GITHUB_ENV

      - name: Run Shared Code
        uses: ./.github/actions/deploy-fargate-app-shared-code
